"use client";
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Calendar2, Notepad2 } from "iconsax-reactjs";
import { Building2 } from "lucide-react";
import { ToothIcon } from "@/components/dental/ToothIcon";
import { TPMedicalIcon } from "@/components/tp-ui";
import rx from "./RxPreviewDocument.module.scss";
import { getAppointmentPatient } from "@/lib/appointment-patients";
function formatDate(value) {
    const dt = new Date(value);
    if (Number.isNaN(dt.getTime()))
        return value;
    return dt.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}
function renderMeta(metaParts) {
    if (metaParts.length === 0)
        return null;
    return (_jsxs("span", { className: rx.metaMuted, children: [" (", metaParts.map((part, index) => (_jsxs("span", { children: [index > 0 ? _jsx("span", { className: rx.metaSep, children: " | " }) : null, part] }, `${part}-${index}`))), ")"] }));
}
function SectionList({ title, rows, icon, }) {
    if (!rows.length)
        return null;
    return (_jsxs("section", { className: rx.section, children: [_jsxs("div", { className: rx.sectionHead, children: [icon ? _jsx("span", { className: rx.icon14, children: icon }) : null, _jsx("h3", { className: rx.sectionTitle, children: title })] }), _jsx("ul", { className: rx.list, children: rows.map((row, index) => (_jsxs("li", { className: rx.listLi, children: [_jsx("span", { className: rx.rowTitle, children: row.title }), renderMeta(row.metaParts)] }, `${title}-${index}`))) })] }));
}
function RxMedicalSectionIcon({ name }) {
    return _jsx(TPMedicalIcon, { name: name, variant: "bulk", size: 14, color: "var(--tp-slate-500)", className: rx.medIcon14 });
}
export function RxPreviewDocument({ snapshot, }) {
    const dentalBlocks = snapshot?.dentalExamination ?? [];
    const firstPageDentalBlocks = dentalBlocks.slice(0, 4);
    const remainingDentalBlocks = dentalBlocks.slice(4);
    const renderLetterhead = () => (_jsxs(_Fragment, { children: [_jsx("header", { className: rx.letterhead, children: _jsx("div", { className: rx.letterRow, children: _jsxs("div", { className: rx.letterLeft, children: [_jsx("div", { className: rx.logoBox, children: _jsx(Building2, { size: 32, className: rx.buildingIcon, strokeWidth: 1.8 }) }), _jsxs("div", { children: [_jsx("p", { className: rx.clinicName, children: "TP Dental Care" }), _jsx("p", { className: rx.docLine, children: "Dr. Umesh Aggarwal, BDS, MDS" }), _jsx("p", { className: rx.metaLine, children: "Reg. ID: DCI-2342342 | +91 78945 61230" }), _jsx("p", { className: rx.metaLine, children: "K9 Sardar Bungalow, Prahladnagar, Ahmedabad" })] })] }) }) }), _jsx("div", { className: rx.rule })] }));
    const renderPatientDetails = () => {
        const pid = snapshot?.patientId ?? "apt-1";
        const ap = getAppointmentPatient(pid);
        return (_jsxs(_Fragment, { children: [_jsx("section", { className: rx.patientSection, children: _jsxs("div", { className: rx.patientRow, children: [_jsxs("div", { className: rx.patientCol, children: [_jsxs("p", { className: rx.patientLine, children: [_jsx("span", { className: rx.patientStrong, children: "Patient Name:" }), " ", ap.name] }), _jsxs("p", { className: rx.patientLine, children: [_jsx("span", { className: rx.patientStrong, children: "Age/Gender:" }), " ", ap.age, " Years, ", ap.genderLabel] }), _jsxs("p", { className: rx.patientLine, children: [_jsx("span", { className: rx.patientStrong, children: "Height/Weight:" }), " —"] }), _jsxs("p", { className: rx.patientLine, children: [_jsx("span", { className: rx.patientStrong, children: "Address:" }), " Prahladnagar, Ahmedabad"] })] }), _jsxs("div", { className: rx.patientRight, children: [_jsxs("p", { className: rx.patientLine, children: [_jsx("span", { className: rx.patientStrong, children: "Patient ID:" }), " ", ap.patientCode] }), _jsxs("p", { className: rx.patientLine, children: [_jsx("span", { className: rx.patientStrong, children: "Mobile:" }), " ", ap.mobile.replace(/^\+91-/, "")] }), _jsxs("p", { className: rx.patientLine, children: [_jsx("span", { className: rx.patientStrong, children: "Blood Group:" }), " ", ap.bloodGroup] })] })] }) }), _jsx("div", { className: rx.rule })] }));
    };
    const renderFooter = () => (_jsxs(_Fragment, { children: [_jsx("div", { className: rx.rule }), _jsx("footer", { className: rx.footer, children: _jsx("p", { className: rx.footerText, children: "support@tpdentalcare.com | www.tpdentalcare.com" }) })] }));
    const renderDentalSection = (blocks, titleSuffix) => {
        if (!blocks.length)
            return null;
        return (_jsxs("section", { className: rx.dentalSection, children: [_jsxs("h3", { className: rx.dentalTitle, children: [_jsx(ToothIcon, { size: 12, color: "var(--tp-slate-500)", variant: "Bulk" }), "Dental Examination", titleSuffix ? ` ${titleSuffix}` : "", _jsxs("span", { className: rx.dentalDate, children: [" ", "(", formatDate(snapshot?.dentalUpdatedAt ?? snapshot?.updatedAt ?? new Date().toISOString()), ")"] })] }), _jsx("div", { className: rx.dentalBlocks, children: blocks.map((block, index) => (_jsxs("div", { className: rx.toothBlock, children: [_jsxs("p", { className: rx.toothLabel, children: [_jsx("span", { className: rx.bullet, children: "\u2022" }), block.toothLabel] }), _jsxs("div", { className: rx.subStack, children: [block.treatmentHistory.length ? (_jsxs("p", { className: rx.subLine, children: [_jsx("span", { className: rx.subBullet, children: "\u2022" }), _jsx("span", { className: rx.subStrong, children: "Treatment History:" }), " ", block.treatmentHistory.map((item, itemIndex) => (_jsxs("span", { children: [itemIndex > 0 ? _jsx("span", { className: rx.comma, children: ", " }) : null, _jsx("span", { children: item.title }), renderMeta(item.metaParts)] }, `th-${itemIndex}`)))] })) : null, block.findings.length ? (_jsxs("p", { className: rx.subLine, children: [_jsx("span", { className: rx.subBullet, children: "\u2022" }), _jsx("span", { className: rx.subStrong, children: "Findings:" }), " ", block.findings.map((item, itemIndex) => (_jsxs("span", { children: [itemIndex > 0 ? _jsx("span", { className: rx.comma, children: ", " }) : null, _jsx("span", { children: item.title }), renderMeta(item.metaParts)] }, `finding-${itemIndex}`)))] })) : null, block.procedures.length ? (_jsxs("p", { className: rx.subLine, children: [_jsx("span", { className: rx.subBullet, children: "\u2022" }), _jsx("span", { className: rx.subStrong, children: "Procedures:" }), " ", block.procedures.map((item, itemIndex) => (_jsxs("span", { children: [itemIndex > 0 ? _jsx("span", { className: rx.comma, children: ", " }) : null, _jsx("span", { children: item.title }), renderMeta(item.metaParts)] }, `proc-${itemIndex}`)))] })) : null, block.overallToothNote ? (_jsxs("p", { className: rx.subLine, children: [_jsx("span", { className: rx.subBullet, children: "\u2022" }), _jsx("span", { className: rx.subStrong, children: "Overall Tooth Notes:" }), " ", block.overallToothNote] })) : null] })] }, `${block.toothLabel}-${index}`))) })] }));
    };
    return (_jsxs("div", { className: rx.page, children: [_jsxs("article", { className: rx.sheet, children: [renderLetterhead(), renderPatientDetails(), _jsx("div", { className: rx.sheetBody, children: !snapshot ? (_jsx("div", { className: rx.emptyPad, children: _jsx("p", { className: rx.emptyText, children: "No Rx data available yet. Add details in Clinical or Dental Examination to preview here." }) })) : (_jsxs("div", { className: rx.contentStack, children: [_jsx(SectionList, { title: "Symptoms", rows: snapshot.symptoms, icon: _jsx(RxMedicalSectionIcon, { name: "Virus" }) }), _jsx(SectionList, { title: "Examination", rows: snapshot.examinations, icon: _jsx(RxMedicalSectionIcon, { name: "medical service" }) }), _jsx(SectionList, { title: "Diagnosis", rows: snapshot.diagnoses, icon: _jsx(RxMedicalSectionIcon, { name: "Diagnosis" }) }), _jsx(SectionList, { title: "Lab Investigation", rows: snapshot.labInvestigations, icon: _jsx(RxMedicalSectionIcon, { name: "Test Tube" }) }), _jsx(SectionList, { title: "Medication (Rx)", rows: snapshot.medications, icon: _jsx(RxMedicalSectionIcon, { name: "Tablets" }) }), _jsx(SectionList, { title: "Advice", rows: snapshot.advice, icon: _jsx(RxMedicalSectionIcon, { name: "health care" }) }), renderDentalSection(firstPageDentalBlocks), snapshot.followUp ? (_jsxs("section", { className: rx.miniSection, children: [_jsxs("h3", { className: rx.dentalTitle, children: [_jsx(Calendar2, { size: 14, color: "var(--tp-slate-500)", variant: "Bulk" }), "Follow Up"] }), _jsx("p", { className: rx.miniBody, children: snapshot.followUp })] })) : null, snapshot.additionalNotes ? (_jsxs("section", { className: rx.miniSection, children: [_jsxs("h3", { className: rx.dentalTitle, children: [_jsx(Notepad2, { size: 14, color: "var(--tp-slate-500)", variant: "Bulk" }), "Additional Notes"] }), _jsx("p", { className: rx.miniBody, children: snapshot.additionalNotes })] })) : null] })) }), renderFooter()] }), remainingDentalBlocks.length > 0 ? (_jsxs("article", { className: rx.sheet, children: [renderLetterhead(), renderPatientDetails(), _jsx("div", { className: rx.continueBody, children: renderDentalSection(remainingDentalBlocks, "(contd.)") }), renderFooter()] })) : null] }));
}
