"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from "react";
import { Plus } from "lucide-react";
import { cn } from "@/lib/utils";
const variantGradients = {
    appointments: "from-[var(--tp-blue-600)] via-[var(--tp-blue-500)] to-[var(--tp-violet-500)]",
    schedule: "from-[var(--tp-violet-600)] via-[var(--tp-violet-500)] to-[var(--tp-blue-500)]",
    analytics: "from-[var(--tp-blue-700)] via-[var(--tp-blue-600)] to-[var(--tp-success-500)]",
};
export function TPAppointmentBanner({ title, subtitle, ctaLabel, ctaIcon, onCtaClick, stats, variant = "appointments", className, }) {
    return (_jsxs("div", { className: cn("relative overflow-hidden rounded-2xl bg-gradient-to-r text-white", variantGradients[variant], className), children: [_jsxs("svg", { className: "pointer-events-none absolute inset-0 h-full w-full opacity-[0.06]", xmlns: "http://www.w3.org/2000/svg", children: [_jsx("defs", { children: _jsx("pattern", { id: "banner-dots", x: "0", y: "0", width: "20", height: "20", patternUnits: "userSpaceOnUse", children: _jsx("circle", { cx: "2", cy: "2", r: "1.5", fill: "currentColor" }) }) }), _jsx("rect", { width: "100%", height: "100%", fill: "url(#banner-dots)" })] }), _jsx("div", { className: "pointer-events-none absolute -right-12 -top-12 h-48 w-48 rounded-full bg-white/[0.06]" }), _jsx("div", { className: "pointer-events-none absolute -bottom-8 -right-4 h-32 w-32 rounded-full bg-white/[0.04]" }), _jsx("div", { className: "pointer-events-none absolute -bottom-16 left-1/3 h-40 w-40 rounded-full bg-white/[0.03]" }), _jsxs("div", { className: "relative z-10 flex items-center justify-between px-6 py-6 lg:px-8 lg:py-7", children: [_jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("h2", { className: "text-xl font-bold tracking-tight lg:text-2xl", style: { fontFamily: "'Mulish', sans-serif" }, children: title }), subtitle && (_jsx("p", { className: "mt-1 text-sm text-white/70 lg:text-base", children: subtitle })), stats && stats.length > 0 && (_jsx("div", { className: "mt-4 flex flex-wrap gap-4 lg:gap-6", children: stats.map((stat, i) => (_jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "text-xl font-bold lg:text-2xl", children: stat.value }), _jsx("p", { className: "text-[11px] text-white/60 uppercase tracking-wide", children: stat.label })] }, i))) }))] }), ctaLabel && (_jsxs("button", { type: "button", onClick: onCtaClick, className: "ml-4 flex shrink-0 items-center gap-2 rounded-[10px] border border-white/35 bg-white/[0.07] px-4 py-2 text-sm font-semibold text-white shadow-sm backdrop-blur-[8px] transition-all hover:bg-white/[0.14] hover:shadow-md active:scale-[0.98]", style: { height: 36 }, children: [ctaIcon || _jsx(Plus, { size: 18 }), _jsx("span", { className: "hidden sm:inline", children: ctaLabel })] }))] })] }));
}
