/**
 * Appointments Module — Sample Data
 * ══════════════════════════════════
 * Realistic sample data for the appointments management page.
 * Follows the same architecture as components/rx/sample-data.ts.
 */

import type {
  Appointment,
  AppointmentTab,
  FilterOption,
} from "./types"

// ─── Sample Appointments ────────────────────────────────────

export const sampleAppointments: Appointment[] = [
  {
    id: "apt-001",
    patient: {
      id: "p-001",
      name: "Rajesh Kumar",
      age: 34,
      gender: "Male",
      phone: "+91 98765 43210",
      uhid: "TP-2024-00142",
      bloodGroup: "B+",
    },
    scheduledTime: "09:00 AM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "OPD",
    status: "queue",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    tokenNumber: 1,
    checkedIn: true,
    checkedInTime: "08:52 AM",
    fee: 500,
    paymentStatus: "paid",
  },
  {
    id: "apt-002",
    patient: {
      id: "p-002",
      name: "Priya Patel",
      age: 28,
      gender: "Female",
      phone: "+91 87654 32109",
      uhid: "TP-2024-00298",
      bloodGroup: "O+",
    },
    scheduledTime: "09:15 AM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "Follow-up",
    status: "queue",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    tokenNumber: 2,
    checkedIn: true,
    checkedInTime: "09:05 AM",
    fee: 300,
    paymentStatus: "paid",
  },
  {
    id: "apt-003",
    patient: {
      id: "p-003",
      name: "Mohammed Ali",
      age: 52,
      gender: "Male",
      phone: "+91 76543 21098",
      uhid: "TP-2024-00076",
      bloodGroup: "A+",
    },
    scheduledTime: "09:30 AM",
    scheduledDate: "2025-06-24",
    duration: 30,
    type: "OPD",
    status: "in-progress",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    tokenNumber: 3,
    checkedIn: true,
    checkedInTime: "09:22 AM",
    fee: 500,
    paymentStatus: "paid",
    notes: "Follow up on hypertension management",
  },
  {
    id: "apt-004",
    patient: {
      id: "p-004",
      name: "Lakshmi Devi",
      age: 45,
      gender: "Female",
      phone: "+91 65432 10987",
      uhid: "TP-2024-00189",
      bloodGroup: "AB+",
    },
    scheduledTime: "10:00 AM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "Teleconsult",
    status: "pending",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    checkedIn: false,
    fee: 400,
    paymentStatus: "pending",
  },
  {
    id: "apt-005",
    patient: {
      id: "p-005",
      name: "Arjun Singh",
      age: 19,
      gender: "Male",
      phone: "+91 54321 09876",
      uhid: "TP-2024-00341",
      bloodGroup: "B-",
    },
    scheduledTime: "10:15 AM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "OPD",
    status: "queue",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    tokenNumber: 5,
    checkedIn: true,
    checkedInTime: "10:01 AM",
    fee: 500,
    paymentStatus: "paid",
  },
  {
    id: "apt-006",
    patient: {
      id: "p-006",
      name: "Sunita Rao",
      age: 38,
      gender: "Female",
      phone: "+91 43210 98765",
      uhid: "TP-2024-00215",
      bloodGroup: "O-",
    },
    scheduledTime: "10:30 AM",
    scheduledDate: "2025-06-24",
    duration: 20,
    type: "Procedure",
    status: "pending",
    doctor: "Dr. Vikram Mehta",
    department: "Dermatology",
    checkedIn: false,
    fee: 1500,
    paymentStatus: "pending",
    notes: "Mole removal consultation",
  },
  {
    id: "apt-007",
    patient: {
      id: "p-007",
      name: "Deepak Verma",
      age: 67,
      gender: "Male",
      phone: "+91 32109 87654",
      uhid: "TP-2024-00058",
      bloodGroup: "A-",
    },
    scheduledTime: "08:30 AM",
    scheduledDate: "2025-06-24",
    duration: 30,
    type: "OPD",
    status: "finished",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    tokenNumber: 0,
    checkedIn: true,
    checkedInTime: "08:20 AM",
    fee: 500,
    paymentStatus: "paid",
    notes: "Diabetes review — HbA1c results discussed",
  },
  {
    id: "apt-008",
    patient: {
      id: "p-008",
      name: "Kavita Nair",
      age: 31,
      gender: "Female",
      phone: "+91 21098 76543",
      uhid: "TP-2024-00167",
      bloodGroup: "B+",
    },
    scheduledTime: "08:00 AM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "Follow-up",
    status: "finished",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    tokenNumber: 0,
    checkedIn: true,
    checkedInTime: "07:55 AM",
    fee: 300,
    paymentStatus: "paid",
  },
  {
    id: "apt-009",
    patient: {
      id: "p-009",
      name: "Ravi Shankar",
      age: 41,
      gender: "Male",
      phone: "+91 10987 65432",
      uhid: "TP-2024-00423",
    },
    scheduledTime: "11:00 AM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "Teleconsult",
    status: "cancelled",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    checkedIn: false,
    fee: 400,
    paymentStatus: "waived",
    notes: "Patient requested cancellation — travel conflict",
  },
  {
    id: "apt-010",
    patient: {
      id: "p-010",
      name: "Meena Gupta",
      age: 55,
      gender: "Female",
      phone: "+91 09876 54321",
      uhid: "TP-2024-00312",
      bloodGroup: "A+",
    },
    scheduledTime: "11:30 AM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "OPD",
    status: "draft",
    doctor: "Dr. Vikram Mehta",
    department: "Dermatology",
    checkedIn: false,
    fee: 600,
    paymentStatus: "pending",
  },
  {
    id: "apt-011",
    patient: {
      id: "p-011",
      name: "Anil Kapoor",
      age: 48,
      gender: "Male",
      phone: "+91 98123 45678",
      uhid: "TP-2024-00445",
      bloodGroup: "O+",
    },
    scheduledTime: "11:45 AM",
    scheduledDate: "2025-06-24",
    duration: 20,
    type: "OPD",
    status: "queue",
    doctor: "Dr. Priya Desai",
    department: "Ophthalmology",
    tokenNumber: 4,
    checkedIn: true,
    checkedInTime: "11:30 AM",
    fee: 700,
    paymentStatus: "paid",
    notes: "Annual eye examination",
  },
  {
    id: "apt-012",
    patient: {
      id: "p-012",
      name: "Sonal Thakur",
      age: 26,
      gender: "Female",
      phone: "+91 87612 34567",
      uhid: "TP-2024-00501",
    },
    scheduledTime: "12:00 PM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "Follow-up",
    status: "pending",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    checkedIn: false,
    fee: 300,
    paymentStatus: "pending",
  },
  {
    id: "apt-013",
    patient: {
      id: "p-013",
      name: "Vikash Joshi",
      age: 36,
      gender: "Male",
      phone: "+91 76512 34890",
      uhid: "TP-2024-00378",
      bloodGroup: "AB-",
    },
    scheduledTime: "09:00 AM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "Emergency",
    status: "finished",
    doctor: "Dr. Priya Desai",
    department: "Ophthalmology",
    tokenNumber: 0,
    checkedIn: true,
    checkedInTime: "08:45 AM",
    fee: 1000,
    paymentStatus: "paid",
    notes: "Acute eye injury — foreign body removal",
  },
  {
    id: "apt-014",
    patient: {
      id: "p-014",
      name: "Neha Saxena",
      age: 33,
      gender: "Female",
      phone: "+91 65412 38907",
      uhid: "TP-2024-00287",
      bloodGroup: "B+",
    },
    scheduledTime: "12:30 PM",
    scheduledDate: "2025-06-24",
    duration: 30,
    type: "OPD",
    status: "queue",
    doctor: "Dr. Rekha Iyer",
    department: "Gynaecology",
    tokenNumber: 6,
    checkedIn: true,
    checkedInTime: "12:15 PM",
    fee: 800,
    paymentStatus: "paid",
  },
  {
    id: "apt-015",
    patient: {
      id: "p-015",
      name: "Suresh Menon",
      age: 72,
      gender: "Male",
      phone: "+91 54312 67890",
      uhid: "TP-2024-00099",
      bloodGroup: "O+",
    },
    scheduledTime: "01:00 PM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "Teleconsult",
    status: "draft",
    doctor: "Dr. Ananya Sharma",
    department: "General Medicine",
    checkedIn: false,
    fee: 400,
    paymentStatus: "pending",
  },
  {
    id: "apt-016",
    patient: {
      id: "p-016",
      name: "Anita Reddy",
      age: 29,
      gender: "Female",
      phone: "+91 43212 56789",
      uhid: "TP-2024-00534",
    },
    scheduledTime: "10:45 AM",
    scheduledDate: "2025-06-24",
    duration: 15,
    type: "Follow-up",
    status: "cancelled",
    doctor: "Dr. Vikram Mehta",
    department: "Dermatology",
    checkedIn: false,
    fee: 300,
    paymentStatus: "waived",
    notes: "No show — rescheduled to next week",
  },
]

// ─── Tab Configuration ──────────────────────────────────────

export const appointmentTabs: AppointmentTab[] = [
  {
    id: "queue",
    label: "Queue",
    count: sampleAppointments.filter((a) => a.status === "queue").length,
    iconActive: "People",       // Bulk variant
    iconInactive: "People",     // Linear variant
  },
  {
    id: "finished",
    label: "Finished",
    count: sampleAppointments.filter((a) => a.status === "finished").length,
    iconActive: "TickCircle",
    iconInactive: "TickCircle",
  },
  {
    id: "cancelled",
    label: "Cancelled",
    count: sampleAppointments.filter((a) => a.status === "cancelled").length,
    iconActive: "CloseCircle",
    iconInactive: "CloseCircle",
  },
  {
    id: "draft",
    label: "Draft",
    count: sampleAppointments.filter((a) => a.status === "draft").length,
    iconActive: "Edit2",
    iconInactive: "Edit2",
  },
  {
    id: "pending",
    label: "Pending",
    count: sampleAppointments.filter((a) => a.status === "pending").length,
    iconActive: "Clock",
    iconInactive: "Clock",
  },
]

// ─── Filter Configuration ───────────────────────────────────

export const appointmentFilters: FilterOption[] = [
  {
    id: "department",
    label: "Department",
    options: [
      { value: "all", label: "All Departments" },
      { value: "General Medicine", label: "General Medicine" },
      { value: "Ophthalmology", label: "Ophthalmology" },
      { value: "Gynaecology", label: "Gynaecology" },
      { value: "Dermatology", label: "Dermatology" },
      { value: "Paediatrics", label: "Paediatrics" },
      { value: "Orthopaedics", label: "Orthopaedics" },
    ],
  },
  {
    id: "doctor",
    label: "Doctor",
    options: [
      { value: "all", label: "All Doctors" },
      { value: "Dr. Ananya Sharma", label: "Dr. Ananya Sharma" },
      { value: "Dr. Vikram Mehta", label: "Dr. Vikram Mehta" },
      { value: "Dr. Priya Desai", label: "Dr. Priya Desai" },
      { value: "Dr. Rekha Iyer", label: "Dr. Rekha Iyer" },
    ],
  },
  {
    id: "type",
    label: "Type",
    options: [
      { value: "all", label: "All Types" },
      { value: "OPD", label: "OPD" },
      { value: "Teleconsult", label: "Teleconsult" },
      { value: "Follow-up", label: "Follow-up" },
      { value: "Emergency", label: "Emergency" },
      { value: "Procedure", label: "Procedure" },
    ],
  },
]

// ─── Doctor List (for nav bar) ──────────────────────────────

export const sampleDoctors = [
  { id: "d-001", name: "Dr. Ananya Sharma", department: "General Medicine", avatarUrl: "" },
  { id: "d-002", name: "Dr. Vikram Mehta", department: "Dermatology", avatarUrl: "" },
  { id: "d-003", name: "Dr. Priya Desai", department: "Ophthalmology", avatarUrl: "" },
  { id: "d-004", name: "Dr. Rekha Iyer", department: "Gynaecology", avatarUrl: "" },
]
